---
# tasks file for ansible-mdadm
#

- name: Main | Include Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts.os_family == "Debian"

- name: Main | Include EL tasks
  ansible.builtin.include_tasks: el.yml
  when: ansible_facts.os_family == "RedHat"

- name: Main | Include wipe_disks tasks
  ansible.builtin.include_tasks: wipe_disks.yml
  when: mdadm_force_wipe | default(false) | bool

- name: Main | Include arrays tasks
  ansible.builtin.include_tasks: arrays.yml
